# Assignment Day3

In [ ]:
! pip install numpy 

In [10]:
import numpy as np

### create a 3x3 matrix with values ranging from 1 to 9

In [18]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [19]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## printing doubled matrix

In [20]:
matrix_doubled = matrix * 2
print(matrix_doubled)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [21]:
import pandas as pd

## Dictionary for Items

In [22]:
data = {
    'product_name': ['Laptop', 'Mouse', 'Keyboard'],
    'price': [1200, 25, 75],
    'stock_quantity': [30, 150, 60]
}

In [23]:
df = pd.DataFrame(data)

## Printing items having stock quantity > 50

In [25]:
filtered_prod = df[df['stock_quantity'] > 50]
print(filtered_prod)

  product_name  price  stock_quantity
1        Mouse     25             150
2     Keyboard     75              60
